### ISSUE TITLE
read image 

### ISSUE THREAD

**Issue by ducbluee** [gtaylor/python-colormath#107]
I see your library currently does not have an image reader. Hope you can improve more.
And I see the current library only comparing monochromatic images, but for images with more than 1 color, what is the solution?
Hope the author will answer soon. Thanks!!!!!

**Comment by KelSolaar** [comment]
Hi @ducbluee,

python-colormath is great for simple computations involving a single colour but is not really appropriate for image processing, the code is not vectorised and will be extremely slow, please see other packages such as https://scikit-image.org/, https://opencv.org/ or https://colour-science.org/. Disclaimer, I maintain the latter.
