### ISSUE TITLE
No BT.2020 color object in pip installed version 

### ISSUE THREAD

**Issue by ZaixiS** [gtaylor/python-colormath#108]
I used pip installed version 3.0.0, strangely, the source code doesn't have BT.2020 color object, I manually copied, but I think it needs to be fixed.

**Comment by KelSolaar** [comment]
Hi @kmd19951,

Yes! This is because the code came after 3.0.0 and has not been released yet! @gtaylor should be able to release a new version though.

**Comment by kmd19951** [comment]
Thanks! Sounds great!
