### ISSUE TITLE
Implement UPLab from Bruce Lindbloom?

### ISSUE THREAD

**Issue by swamidass** [gtaylor/python-colormath#109]
How difficult it is it to add a UPLab color? The ICC profile is attached here. Alternatively, an approach to add custom colorspaces based on an ICC profile would solve the problem in another more flexible way.

http://www.brucelindbloom.com/index.html?UPLab.html

**Comment by KelSolaar** [comment]
Hi @swamidass,

UPLab is a LUT based colourspace and the LUT is rather large, i.e. 1.2mb which is probably not advisable to package as it would increase massively the size of the project. The other issue is that interpolating through that LUT would require code that does not exist in `python-colormath`, it is quite a significant undertaking.

**Comment by swamidass** [comment]
So, I managed to sort of get this to work with Pillow and their interface to littleCMS, but it uses integer math. 

Have you thought of building an interface between colormath and Pillow? That would give you a way to make use of any ICC profile.

**Comment by gtaylor** [comment]
This sounds significant enough to be grounds for a separate module. Going to close this issue as there are no plans to pull in the LUT or the Pillow interface. Thanks for raising, @swamidass!
