### ISSUE TITLE
D50 Spectral Power Distribution

### ISSUE THREAD

**Issue by tenberg** [gtaylor/python-colormath#47]
Greg & | Michael,

I was doing some color conversion testing using colormath and I have a few questions. For example, I took one spectral color, converted it to CIELAB (D50/2) and noticed that the results I calculated in Matlab are slightly different from those of colormath. I double checked my Matlab results with some internal / external software here at work and was able to get agreement  in the 2nd/3rd decimal point. Colormath was different in the 1st decimal point in the a*/b* channels. Long story short, I did some digging and the color matching functions appear correct, but I noticed some differences in the D50 illuminant spectral power distribution that may be causing the differences. I don't have anything conclusive yet, but I was wondering where the colormath D50 spectral values were obtained.

Anyway, here is an example.

spc = SpectralColor(
        observer='2', illuminant='d50',
        spec_380nm=0.1115, spec_390nm=0.2129, spec_400nm=0.4294,
        spec_410nm=0.7099, spec_420nm=0.8188, spec_430nm=0.8461,
        spec_440nm=0.8615, spec_450nm=0.8693, spec_460nm=0.8696,
        spec_470nm=0.8618, spec_480nm=0.8448, spec_490nm=0.8129,
        spec_500nm=0.7708, spec_510nm=0.7251, spec_520nm=0.6752,
        spec_530nm=0.6365, spec_540nm=0.6244, spec_550nm=0.6118,
        spec_560nm=0.583, spec_570nm=0.5608, spec_580nm=0.5583,
        spec_590nm=0.5669, spec_600nm=0.5669, spec_610nm=0.5548,
        spec_620nm=0.5444, spec_630nm=0.5475, spec_640nm=0.5697,
        spec_650nm=0.6026, spec_660nm=0.6356, spec_670nm=0.6538,
        spec_680nm=0.6553, spec_690nm=0.6487, spec_700nm=0.6376,
        spec_710nm=0.6261, spec_720nm=0.6123, spec_730nm=0.5997)

LabColor(lab_l=82.70112227758003,lab_a=-1.207624444272526,lab_b=-18.721833945990383)

In Matlab, I'm getting [82.7032   -1.1449  -18.8222] which agrees with software I use at work.

Also, this could due to user error, so don't be afraid to tell me I messed up. I'm still learning python.

(I also noticed some differences in D65 when compared to the data I found on the CIE's website
http://www.cie.co.at/index.php/LEFTMENUE/index.php?i_ca_id=298)

Thanks,

Ed

**Comment by gtaylor** [comment]
Unless there are any objections, I'll close this one. I'm open to feedback as to whether this is necessary, but don't have strong enough feelings to take this task on myself.
