### ISSUE TITLE
changing colorspace for whole image

### ISSUE THREAD

**Issue by sagnik** [gtaylor/python-colormath#50]
Is there a way to convert a 3D RGB numpy array to LAB space directly (instead of going through all the pixels separately) ?

**Comment by gtaylor** [comment]
I don't think we have a way currently, but maybe I'm missing something obvious. Any ideas, @MichaelMauderer?

**Comment by sagnik** [comment]
Yes, I looked into the open issues, seems @MichaelMauderer  opened the same issue in 2014.

**Comment by MichaelMauderer** [comment]
Yeah this is what I talked about in issue #45.

This doesn't currently work as there a plenty of assumptions in the code about colors consisting of floats (e.g., explicit conversions to float, string formatting and float comparisons).

It would probably be a lot of work to allow this as basically everything has to be rewritten.

Your best bet might be to use [`numpy.vectorize`]( http://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html#numpy-vectorize) to wrap the conversion functions. This will spare you writing a manual loop, but it won't give you the expected performance benefit.

**Comment by gtaylor** [comment]
Let's go on ahead and label this as needing feedback. We'll see how many other people chime in to figure out how to prioritize this. It'd probably be way too much of a refactor to land in our upcoming release, but it never hurts to have an idea of where we might be heading longer term.

If we don't see much activity within a few months, we'll close this.

**Comment by astromz** [comment]
Hi! I found this thread from >2 yrs ago. Any update on this? Thanks!

**Comment by KelSolaar** [comment]
@astromz: Any details on what you are trying to achieve? [Colour](http://colour.readthedocs.io/en/develop/colour.models.rgb.rgb_colourspace.html#colour.models.rgb.rgb_colourspace.RGB_to_RGB) and [scikit-image](http://scikit-image.org/docs/stable/api/skimage.color.html) should be able to do that without much issues.

Disclaimer: I'm a Colour maintainer.

**Comment by astromz** [comment]
@KelSolaar Thanks for getting back to me! I've found a rgb2lab function in scikit-image, which is exactly what I wanted.

**Comment by KelSolaar** [comment]
@astromz: Excellent, glad it was helpful :)

**Comment by gtaylor** [comment]
I'm happy letting scikit-image handle this. Closing!
