### ISSUE TITLE
networkx dependency not mentioned in documentation

### ISSUE THREAD

**Issue by andreas-h** [gtaylor/python-colormath#53]
on the installation page of the documentation, it says that *The only other requirement is NumPy.*. However, it seems that the networkx package is also a dependency:

    File "setup.py", line 39, in <module>
      install_requires=['numpy', 'networkx'],

**Comment by gtaylor** [comment]
Thanks for pointing this out. I sure would love a pull request if you could spare the time. Otherwise, I'll try to get to this when I can.
