### ISSUE TITLE
RGB to Lab to RGB: rounding issue

### ISSUE THREAD

**Issue by FlavienMakesInfographics** [gtaylor/python-colormath#58]
Hi, 
I have a problem with rounding errors when converting from Lab to RGB (this is an extract from Jupyter notebook):

```
red_color = "#ff0000"
rgb = sRGBColor.new_from_rgb_hex(red_color)
rgb
# result: 
sRGBColor(rgb_r=1.0,rgb_g=0.0,rgb_b=0.0)
```

```
lab_color = convert_color(rgb, LabColor)
lab_color
# result: LabColor(lab_l=53.23896002513146,lab_a=80.09045298802708,lab_b=67.2013836595967)
```

```
convert_color(lab_color, sRGBColor)
# result: sRGBColor(rgb_r=1.000000195385799,rgb_g=0.0,rgb_b=2.37945055932276e-07)
```

The rounding error is problematic when you want to convert straightforwardly to HEX afterwards.

**Comment by KelSolaar** [comment]
Hexadecimal conversion is meant to work on integers, it is not surprising that at some point you may not able to do the roundtrip.

**Comment by FlavienMakesInfographics** [comment]
Hi, 
thanks for the reply. But it is problematic independently of HEX. The value of rgb_r is larger than one.

**Comment by KelSolaar** [comment]
True!

After a quick inspection I'm tempted to say it is coming from the [sRGB NPM and its reverse](https://github.com/gtaylor/python-colormath/blob/master/colormath/color_objects.py#L646) being rounded inadequately:

```python
M1 = np.array(((3.24071, -1.53726, -0.498571),
               (-0.969258, 1.87599, 0.0415557),
               (0.0556352, -0.203996, 1.05707)))
M2 = np.array(((0.412424, 0.357579, 0.180464),
               (0.212656, 0.715158, 0.0721856),
               (0.0193324, 0.119193, 0.950444)))

print(np.dot(np.dot(np.eye(3), M1), M2))

# [[  1.00000044e+00  -1.19193000e-07  -3.61540000e-07]
#  [ -1.36053732e-06   9.99996099e-01  -3.46237200e-07]
#  [  1.84168000e-08  -4.76772000e-08   1.00000042e+00]]
```

**Comment by gtaylor** [comment]
Floating point math is fraught with fun stuff:

https://docs.python.org/2/tutorial/floatingpoint.html

I don't know if there's anything actionable on our end without moving to Decimals everywhere (bleh).

Closing unless something new comes up (re-open in that case).

**Comment by KelSolaar** [comment]
Well, if you were defining `xyz_to_rgb` as the invert of the NPM (`rgb_to_xyz`) or the reverse you wouldn't get the rounding / truncation issues you have right now. We are doing it this way in Colour and it does allow for a perfect roundtrip: https://github.com/colour-science/colour/blob/develop/colour/models/dataset/srgb.py#L84

Feel free to grab the NPM too as it is more precise than the one you have currently too.
