### ISSUE TITLE
Color distance not symmetric for Delta E (CMC)

### ISSUE THREAD

**Issue by ranjanMohit** [gtaylor/python-colormath#62]
Apologies if this is expected behaviour, but i found this counter intuitive.
Delta E(CMC) distance between 2 color is not symmetric.

```
>>> from colormath.color_objects import LabColor
>>> l1 = LabColor(-10.2072, 1.0841, 3.7213)
>>> l2 = LabColor(-8.1522, 0.4888, 0.1684)
>>> from colormath.color_diff import delta_e_cmc
>>> delta_e_cmc(l1, l2)
4.694164003774187
>>> delta_e_cmc(l2, l1)
5.736355541601584
>>>

```

**Comment by jlmcgehee21** [comment]
∆E CMC is not symmetric by nature: https://en.wikipedia.org/wiki/Color_difference#CMC_l:c_.281984.29

While I'm not a developer on this project, I have used it extensively (including the CMC calculation)

**Comment by ranjanMohit** [comment]
Thanks @jlmcgehee21 for link.
Which distance calculation you will suggest for visual interpretation ? Also, CMC not being symmetric can lead to potential issues (is there any convention to follow while using CMC ?)

**Comment by jlmcgehee21** [comment]
With CMC the convention is to define a _reference sample_ I believe here, you pass the _reference_ first.

For a good symmetrical ∆E calculation, I would use CIE2000.

**Comment by gtaylor** [comment]
If this isn't a colormath bug, let's get this issue closed. You can feel free to discuss this more here, though.

**Comment by ranjanMohit** [comment]
Sure @gtaylor . Closing it.
