### ISSUE TITLE
Upscaled RGB Range

### ISSUE THREAD

**Issue by mark-meyer** [gtaylor/python-colormath#66]
I was looking into an earlier issue (clamped methods of BaseRGBColor does not work as expected #64) and am confused by the 1-255 range for upscaled RGB values.
 
The Documentation says:

>  When converting to RGB, this can cause some of the coordinates to end up being out of the acceptable range (0.0-1.0 or 1-255, depending on whether your RGB color is upscaled)…

Why is the upscaled RGB range not 0-255? With the range 1-255 what upscaled value maps to black with a non-upscaled value of (0.0, 0.0, 0.0)? 
    
    >>> from colormath.color_objects import sRGBColor
    >>> rgb = sRGBColor( 1,1, 1,is_upscaled=True)
    >>> rgb
    sRGBColor(rgb_r=0.00392156862745098,rgb_g=0.00392156862745098,rgb_b=0.00392156862745098)

**Comment by gtaylor** [comment]
That's probably a typo. What happened when you tried upscaled + RGB = 0,0,0?

**Comment by markmeyerphoto** [comment]
Using (0,0,0) works as expected. But so does (-10, 0, 0). The question really only comes up when we want to clamp the values. The code for clamped upscaled values is broken at the moment as pointed out in the earlier issue. It's a quick fix, but I want to make sure I wasn't misunderstanding something because the 1-255 range is in the code too, which made it seem like more than a typo: 
    
    def _clamp_rgb_coordinate(self, coord):
    …
    return min(max(coord, 1), 255)

and the comments on init:

    def __init__(self, rgb_r, rgb_g, rgb_b, is_upscaled=False):
        """
        :param float rgb_r: R coordinate. 0...1. 1-255 if is_upscaled=True.
        :param float rgb_g: G coordinate. 0...1. 1-255 if is_upscaled=True.
        :param float rgb_b: B coordinate. 0...1. 1-255 if is_upscaled=True.
        :keyword bool is_upscaled: If False, RGB coordinate values are
            beteween 0.0 and 1.0. If True, RGB values are between 1 and 255.
        """
I can submit a PR that fixes clamping issue and clamps to 0-255, which seems right and works for every case I can think of.

**Comment by gtaylor** [comment]
It seems like a typo or some half assed way to prevent issues with zero
operations. I guess we'd need to see if we could shake any of those out
after lowering the floor to 0.

**Comment by markmeyerphoto** [comment]
I'll take a look. My hunch is that there won't be many issues since the values appear to be primarily represented as 0.0-1.0 floats internally and seem to only be upscaled as a convenience to user who want regular 0-255 values.

**Comment by gtaylor** [comment]
It's been a long time since I've looked at this, so you are probably right.
Happy to talk over a PR for this if we can test it pretty well.

**Comment by markmeyerphoto** [comment]
I've search through the code and can't find anywhere where clamped, upscaled values are used internally. Places were the the upscaled values are used like get_rgb_hex() don't clamp the values so rgb(0, 0, 0) ends up where it should be '#000000.' I pushed a PR - there's only one code line changed in addition to some comments.

**Comment by MartyMacGyver** [comment]
Why was the change withdrawn?

**Comment by MartyMacGyver** [comment]
I'm curious why the change was withdrawn?

I've added a PR correct this (and updates the associated documentation) based on the following a

- The non-upscaled decimal range for an RGB color is `[0.0 .. 1.0]`
- The upscaled uint8 range for an RGB color is `[0 .. 255]`
- The upscaled decimal range for RGB would be [`0.0 .. 255.0`], **but who uses an _upscaled_ RGB value in floating point?**

Looking at `get_upscaled_value_tuple()`, I'd think clamping would work virtually the same way, and really ought to be returning an integer. However, that isn't part of the scope of this PR.
