### ISSUE TITLE
Custom lightsource and material interaction

### ISSUE THREAD

**Issue by onegobo** [gtaylor/python-colormath#68]
I apologize beforehand if this functionality is already in ColorMath and this should turn out an error or lack of knowledge on my side:

Is there a way of doing math on the interaction between surface and light source color? 

Simple example: A saturated orange tone surface X is lit with a saturated blue tone filtered light Y - presumably the apperance is a close blockout, a dark grey. 

Advanced example: An array of surface colors A under a light source Z, which got a very rugged and bad spectral distribution. What is happening? What is left of an orange or a limegreen? What is the appearance?

How to calc for those multiplication effects? Is that possible already? 

Thanks a lot, much appreciated!
Axel

**Comment by gtaylor** [comment]
Sorry, I don't have much for guidance on this. I'm pretty rusty on my color math.
