### ISSUE TITLE
Converting RGB to LAB

### ISSUE THREAD

**Issue by mobcdi** [gtaylor/python-colormath#69]
Hi,

I'm having trouble converting rgb to lab and getting the same output as online color converters when I validate it

```
from colormath.color_objects import XYZColor, sRGBColor,LabColor
from colormath.color_conversions import convert_color

rgb = sRGBColor(82, 103, 20)
xyz = convert_color(rgb, XYZColor)
lab = convert_color(xyz,LabColor)
```
These are the outputs I get when I run the code

```
sRGBColor(rgb_r=82.0,rgb_g=103.0,rgb_b=20.0)
XYZColor(xyz_x=35774.970599858236,xyz_y=50079.394305847025,xyz_z=8891.813639311802)
LabColor(lab_l=4259.737273603557,lab_a=-1673.389793872623,lab_b=3344.4187345102782)
```
But when i use [color converter](http://colormine.org/color-converter) I get a Lab value of
CIE-L*ab
L  
40.48337507852484
A  
-20.25190041462896
B  
40.96416270077111
 
Where am I going wrong?

**Comment by hemavakade** [comment]
Consider normalizing the values before feeding it inside `sRGBColor` or pass an additional argument
`is_upscaled=True` and it is internally scaled down between 0-1.

```color = np.array([82, 103, 20])/255.0
 rgb = sRGBColor(color[0], color[1], color[2])
```

or simply,

```
 rgb = sRGBColor(rgb_r = color[0], rgb_g =color[1], rgb_b = color[2], is_upscaled=True)
```

**Comment by gtaylor** [comment]
Good suggestion, @hemavakade. Going to take the lack of response from @mobcdi as "This worked for me, woohoo!" and close this.

**Comment by mfeif** [comment]
So this means one can't make (s)rgb colors with integer values?!?

**Comment by ochavezwilfredc** [comment]
> Considere la posibilidad de normalizar los valores antes de introducirlos dentro `sRGBColor`o pase un argumento adicional 
> `is_upscaled=True`y se reduce internamente entre 0-1.
> 
> ```
>  rgb = sRGBColor(color[0], color[1], color[2])
> ```
> o simplemente,
> 
> ```
>  rgb = sRGBColor(rgb_r = color[0], rgb_g =color[1], rgb_b = color[2], is_upscaled=True)
> ```

Muchas gracias
