### ISSUE TITLE
Error when importing color_conversions module

### ISSUE THREAD

**Issue by RolandMunsil** [gtaylor/python-colormath#78]
Using colormath 2.1.1, python 3.6.2. When I try to import `convert_color` I get the following error:
```
Traceback (most recent call last):
  File "[removed]", line 2, in <module>
    from colormath.color_conversions import convert_color
  File "C:\Program Files\Python36\lib\site-packages\colormath\color_conversions.py", line 167, in <module>
    def Spectral_to_XYZ(cobj, illuminant_override=None, *args, **kwargs):
  File "C:\Program Files\Python36\lib\site-packages\colormath\color_conversions.py", line 159, in decorator
    _conversion_manager.add_type_conversion(start_type, target_type, f)
  File "C:\Program Files\Python36\lib\site-packages\colormath\color_conversions.py", line 125, in add_type_conversion
    self.conversion_graph.add_edge(start_type, target_type, {'conversion_function': conversion_function})
TypeError: add_edge() takes 3 positional arguments but 4 were given
Press any key to continue . . .
```

To reproduce all you need is a python file with one line: `from colormath.color_conversions import convert_color`.

**Comment by Azd325** [comment]
You have to downgrade networkx to >2.0  for colormath 2.1 because the requirements are to too loosely defined in the setup.py

**Comment by RolandMunsil** [comment]
Did you mean <2.0? Or do I have to upgrade to the dev version of networkx (2.1)?

**Comment by Azd325** [comment]
Yes, I mean <2.0 :)
The have only to release the latest version to pypi, then it will work again.

**Comment by RolandMunsil** [comment]
Alright, downgraded to 1.11 and now it's working perfectly. Thanks for your help!
