### ISSUE TITLE
Investigate intent of "colormath.color_conversions._RGB_SPACES" private attribute.

### ISSUE THREAD

**Issue by KelSolaar** [gtaylor/python-colormath#84]
The `colormath.color_conversions._RGB_SPACES` private attribute is defined but not used anywhere in the codebase, I would like to know what was the intent behind it: https://github.com/gtaylor/python-colormath/blob/master/colormath/color_conversions.py#L59

**Comment by gtaylor** [comment]
This is probably dead code
