### ISSUE TITLE
Create "SpectralColor" object from "ndarray". 

### ISSUE THREAD

**Issue by imansaj** [gtaylor/python-colormath#89]
Hello. how can i  import a numpy array containing intensity values for each wavelength as a spectralcolor object.

tnx

**Comment by KelSolaar** [comment]
Hi @imansaj,

I think you should be able to pass the `ndarray` using the `*` operator, although I have not tried:

```python
SpectralColor(*my_array)
```

This assumes that your array spectral domain is as follows: [340, 830] with 10nm bins.

The instantiation could be improved but it requires a significant amount of work. If you are going down hard the spectral road, I would recommend using [Colour](https://github.com/colour-science/colour) which is more mature on that end.

**Comment by imansaj** [comment]
Great It worked, thank you very much.

**Comment by KelSolaar** [comment]
Glad to hear! :)
